In [1]:
import pandas as pd

df = pd.read_csv("../data/df_road_file.csv")
df["lrp"] = df["lrp"].astype(str)
df.head()

,road,id,model_type,name,lat,lon,length,condition,lrp
0,N1,1000000,source,source,22.358667,91.782277,0,NaN,LRP235b
1,N1,1000001,link,link 1,22.369138,91.777666,1257,NaN,LRP235a
2,N1,1000002,link,link 2,22.369166,91.774194,357,NaN,LRP235
3,N1,1000003,link,link 3,22.376225,91.770543,870,NaN,LRP234b
4,N1,1000004,link,link 4,22.376472,91.770416,30,NaN,LRP234a

In [2]:
# output of charactersitics of the top 5 bridges selected for investment

bridge_names = ["DHOOM GHAT PC GIRDER",
                "LANGOLBANDO PC GIDER BRIDGE",
                "PURPU DURGAPURE BOX CUL",
                "DARIKANDI BRIDGE (R)",
                "SHADIPUR BOX CULVERT"
                ]
top_5_bridges = df[df["name"].isin(bridge_names)]
top_5_bridges.sort_values(by="length", ascending=False)

,road,id,model_type,name,lat,lon,length,condition,lrp
236,N1,1000236,bridge,DHOOM GHAT PC GIRDER,22.915667,91.525944,221,B,LRP168a
598,N1,1000598,bridge,LANGOLBANDO PC GIDER BRIDGE,23.654986,90.575902,160,B,LRP017c
594,N1,1000594,bridge,DARIKANDI BRIDGE (R),23.650889,90.582638,20,B,LRP018a
197,N1,1000197,bridge,PURPU DURGAPURE BOX CUL,22.823944,91.552833,12,C,LRP178a
586,N1,1000586,bridge,SHADIPUR BOX CULVERT,23.634111,90.597027,10,B,LRP020b

In [3]:
# longest bridges
bridges_df = df[df["model_type"]=="bridge"]
long_bridges = bridges_df.sort_values(by="length", ascending=False)
long_bridges

,road,id,model_type,name,lat,lon,length,condition,lrp
236,N1,1000236,bridge,DHOOM GHAT PC GIRDER,22.915667,91.525944,221,B,LRP168a
598,N1,1000598,bridge,LANGOLBANDO PC GIDER BRIDGE,23.654986,90.575902,160,B,LRP017c
256,N1,1000256,bridge,LAMUA BRIDGE,22.962417,91.441694,94,B,LRP156a
546,N1,1000546,bridge,Bhaber char Bridge(R),23.556444,90.658861,30,A,LRP031b
558,N1,1000558,bridge,Anarpara Bridge (R),23.572166,90.645111,30,A,LRP029a
...,...,...,...,...,...,...,...,...,...
563,N1,1000563,bridge,Bridge end,23.582583,90.638139,0,B,LRP028a
551,N1,1000551,bridge,Bridge start,23.562056,90.652347,0,B,LRP030c
601,N1,1000601,bridge,Bridge start,23.655972,90.574333,0,B,LRP017a
605,N1,1000605,bridge,Langalbandhu bridge,23.659111,90.569722,0,B,LRP016b
632,N1,1000632,bridge,Kachpur bridge,23.702111,90.515778,0,B,LRP008a